services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: metro.proxy.rlwy.net
      - key: DB_PORT
        value: 34855
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your_actual_password